### ISSUE TITLE
Template strings

### ISSUE THREAD

**Issue by sergebat** [dfcreative/fps-indicator#3]
This modules is neat and lightweight, but uses template strings. This means that out of box it is uncompatible with IE11 at least. Maybe it worths removing this dependency? Or at least documenting that users need to use Babel or other transpiler for ES6 features? Or maybe including transpilation step into the lib itself?

**Comment by dfcreative** [comment]
@sergebat thank you! Fixed https://github.com/dfcreative/fps-indicator/commit/66a86a36af64c3b3ed2f520726cee789e22c40ae
